<a href="https://colab.research.google.com/github/ericmuga253/Python-Data-/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:



# Create an array with zeros
arr = np.array([1, 0, 2, 0])

# Save current numpy error settings
old_settings = np.seterr(all='ignore')

# Perform division by zero
result = np.divide(arr, 0)

# Restore the previous numpy error settings
np.seterr(**old_settings)

print("Result after division:", result)


Result after division: [inf nan inf nan]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-6-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-04-24
Today: 2024-04-25
Tomorrow: 2024-04-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
from datetime import datetime, timedelta

# Define the start date as July 1, 2016
start_date = datetime(2016, 7, 1)

# Define the end date as July 31, 2016
end_date = datetime(2016, 7, 31)

# Initialize a list to store the dates
dates_in_july_2016 = []

# Loop through each date from start_date to end_date
current_date = start_date
while current_date <= end_date:
    # Add the current date to the list
    dates_in_july_2016.append(current_date)
    # Move to the next day
    current_date =current_date + timedelta(days=1)

# Print the list of dates
for date in dates_in_july_2016:
    print(date)


2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [3]:
import numpy as np
A=np.array([3, 8, 6])
B=np.array([5, 2 ,8])


#Computing (A + B)
F = (A + B)
print(F)

#Compute (-A/2)
C = (A * -1)
print(C)
D = (C/2)
print(D)

# Compute ((A+B)*(-A/2))
E = (F * D)
print(E)

[ 8 10 14]
[-3 -8 -6]
[-1.5 -4.  -3. ]
[-12. -40. -42.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:


array = np.random.randint(0, 4, size=(5, 5))  # Generate a 5x5 array of random numbers between 0 and 1
print(array)


[[1 3 2 2 1]
 [3 2 1 2 0]
 [0 2 0 1 0]
 [0 1 3 2 1]
 [2 2 2 1 0]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def integer_generator():
  array = np.arange(0, 10)
  print(np.array(array))
integer_generator()

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
array=np.random.random(10)
print(array)

[0.51809328 0.63271981 0.7728076  0.52789365 0.75780244 0.14046758
 0.37870378 0.32178024 0.57315516 0.7960702 ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array=np.random.random(10)
array_sorted=np.sort(array)
print(array_sorted)

[0.10381303 0.13459774 0.2428309  0.29651324 0.30003072 0.59223913
 0.65402778 0.85864196 0.91747393 0.92704271]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:


# Define a small array
small_array = np.array([1, 2, 3, 4, 5])

# Sum the elements using Python's built-in sum() function
sum_result = sum(small_array)

print("Sum of the array:", sum_result)


Sum of the array: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
array1=np.random.random(10)
array2=np.random.random(10)
print(array1==array2)

[False False False False False False False False False False]


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:


# Generate random Cartesian coordinates (10x2 matrix)
cartesian_coords = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Convert to polar coordinates
rho = np.hypot(x, y)
theta = np.arctan2(y, x)

# Combine rho and theta into a 10x2 matrix of polar coordinates
polar_coords = np.column_stack((rho, theta))

print("Cartesian coordinates:")
print(cartesian_coords)
print("\nPolar coordinates:")
print(polar_coords)


Cartesian coordinates:
[[0.0238784  0.01172711]
 [0.95947391 0.73410084]
 [0.81254196 0.8874579 ]
 [0.56788233 0.88428885]
 [0.9609403  0.98058029]
 [0.95733999 0.8330715 ]
 [0.11406528 0.97167806]
 [0.7899816  0.62524855]
 [0.94836492 0.9839703 ]
 [0.54223107 0.40903929]]

Polar coordinates:
[[0.02660268 0.45651665]
 [1.20809529 0.6531001 ]
 [1.20324809 0.82943787]
 [1.05093155 0.99993035]
 [1.37293261 0.7955136 ]
 [1.26905791 0.71610152]
 [0.97835022 1.45394114]
 [1.0074754  0.66951945]
 [1.36659927 0.80382217]
 [0.67921107 0.64628787]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
from re import A
array=np.random.rand(10)
print(array)

[0.25286856 0.33632947 0.43538561 0.29030719 0.53547052 0.22119588
 0.03517391 0.18966376 0.85238617 0.09620788]


In [ ]:
maximum_value=np.max(array)
array[array == maximum_value] = 10
print(array)




[ 0.25286856  0.33632947  0.43538561  0.29030719  0.53547052  0.22119588
  0.03517391  0.18966376 10.          0.09620788]
