<a href="https://colab.research.google.com/github/ericmuga253/Python-Data-/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np
array=np.array([3,7,1,2,6,3])
given_value=4

absolute_diff=np.abs(array-given_value)
nearest_index=np.argmin(absolute_diff)

nearest_value=array[nearest_index]

print('array', array)
print('given value', given_value)
print('nearest value', nearest_value)

array [3 7 1 2 6 3]
given value 4
nearest value 3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [7]:
# Define the two arrays representing the piles of building blocks
pile1 = [[1, 2, 3]]
pile2 = [[4], [5], [6]]

# Initialize the total number of blocks to 0
total_blocks = 0

# Iterate through each block in the first pile
for block in pile1[0]:
    # Add the value of the block to the total number of blocks
    total_blocks += block

# Iterate through each block in the second pile
for row in pile2:
    for block in row:
        # Add the value of the block to the total number of blocks

        total_blocks += block

print("Total number of blocks:", total_blocks)

Total number of blocks: 21


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class Array_class:
  def __init__(self, name):
    self.name = name

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
import numpy as np

# Given vector X
X = np.array([1, 2, 3, 4, 5])

# Index list I
I = np.array([0, 1, 1, 3, 4])

# Initialize array F with zeros
F = np.zeros(np.max(I) + 1)

# Accumulate elements of X into F based on index list I
np.add.at(F, I, X)

print("Accumulated array F:", F)


Accumulated array F: [1. 5. 0. 4. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np

# Assuming 'array' is your four-dimensional array
# Create a sample 4D array for demonstration
array = np.random.randint(0, 10, (2, 3, 4, 5))

# Get the sum over the last two axes
sum_last_two_axes = np.sum(array, axis=(-1, -2))

print("Original array shape:", array.shape)
print("Sum over the last two axes shape:", sum_last_two_axes.shape)
print("Sum over the last two axes:")
print(sum_last_two_axes)


Original array shape: (2, 3, 4, 5)
Sum over the last two axes shape: (2, 3)
Sum over the last two axes:
[[100  98  91]
 [ 88  93  81]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [3]:
import numpy as np

# Example one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Example subset indices vector S
S = np.array([0, 0, 1, 1, 2, 2, 3, 3, 3, 3])

# Find unique subset indices
unique_indices = np.unique(S)

# Initialize an empty list to store subset means
subset_means = []

# Iterate over unique indices and compute mean for each subset
for index in unique_indices:
    subset = D[S == index]  # Select elements of D where S equals the current index
    subset_mean = np.mean(subset)  # Compute mean of the subset
    subset_means.append(subset_mean)

# Convert the list of subset means to a NumPy array
subset_means = np.array(subset_means)

print("One-dimensional vector D:", D)
print("Subset indices vector S:", S)
print("Means of subsets:", subset_means)


One-dimensional vector D: [ 1  2  3  4  5  6  7  8  9 10]
Subset indices vector S: [0 0 1 1 2 2 3 3 3 3]
Means of subsets: [1.5 3.5 5.5 8.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [1]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute dot product
C = np.dot(A, B)

# Extract diagonal elements
diagonal = np.diag(C)

print("Diagonal of the dot product:", diagonal)


Diagonal of the dot product: [30 69 90]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [13]:
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Insert 3 consecutive zeros between each value
new_vector = np.zeros(len(original_vector) * 4 - 3)
new_vector[::4] = original_vector

print("Original vector:", original_vector)
print("New vector with 3 consecutive zeros interleaved:", new_vector)


Original vector: [1 2 3 4 5]
New vector with 3 consecutive zeros interleaved: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [2]:
import numpy as np

# Create a 3D array of dimension (5, 5, 3)
array_3d = np.random.rand(5, 5, 3)

# Create a 2D array of dimension (5, 5)
array_2d = np.random.rand(5, 5)

# Multiply the 3D array by the 2D array using broadcasting
result = array_3d * array_2d[:,:,np.newaxis]

print("Array of dimension (5, 5, 3):\n", array_3d)
print("\nArray with dimensions (5, 5):\n", array_2d)
print("\nResult after multiplication:\n", result)


Array of dimension (5, 5, 3):
 [[[0.192713   0.0191257  0.66920715]
  [0.43912184 0.72049578 0.64138374]
  [0.13585139 0.10277201 0.70850456]
  [0.82296397 0.84203241 0.60894159]
  [0.81160916 0.05807878 0.45993051]]

 [[0.86280522 0.38409385 0.10855624]
  [0.02445408 0.44852746 0.30191437]
  [0.61877457 0.17502505 0.21666487]
  [0.74169143 0.64890732 0.22953997]
  [0.16087853 0.62368476 0.35912484]]

 [[0.64726441 0.29606958 0.75076519]
  [0.57561755 0.88193216 0.68671815]
  [0.43634337 0.39092166 0.41207735]
  [0.51118232 0.67564226 0.85848314]
  [0.73096241 0.37874698 0.14163614]]

 [[0.1928654  0.59848116 0.83904496]
  [0.29310409 0.48148524 0.65152928]
  [0.8593478  0.99030568 0.79681841]
  [0.64392696 0.7273001  0.17230177]
  [0.33910825 0.37403173 0.39960101]]

 [[0.36947593 0.76496998 0.99756236]
  [0.75906625 0.20681268 0.74432049]
  [0.09492195 0.97418082 0.07017703]
  [0.22949154 0.81199411 0.86858886]
  [0.87485123 0.69269078 0.52280473]]]

Array with dimensions (5, 5):
 [[

#### 72. How to swap two rows of an array? (★★★)

In [15]:
array=np.array([[2,3,4],

                [4,5,6]])

array[[1, 0]]=array[[0, 1]]
print(array)

[[4 5 6]
 [2 3 4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [6]:
import numpy as np

# Example set of 10 triplets describing 10 triangles (with shared vertices)
triplets = np.array([
    [(0, 0), (1, 0), (0, 1)],
    [(1, 0), (1, 1), (0, 1)],
    [(1, 1), (2, 1), (1, 2)],
    [(2, 1), (2, 2), (1, 2)],
    [(0, 1), (1, 1), (0, 2)],
    [(1, 1), (2, 1), (1, 2)],
    [(2, 1), (3, 1), (2, 2)],
    [(3, 1), (3, 2), (2, 2)],
    [(0, 2), (1, 2), (0, 3)],
    [(1, 2), (2, 2), (1, 3)]
])

# Extract unique line segments
line_segments = set()
for triplet in triplets:
    for i in range(3):
        # Convert numpy arrays to tuples before sorting
        line_segments.add(tuple(sorted([tuple(triplet[i]), tuple(triplet[(i + 1) % 3])])))

print("Unique line segments composing all the triangles:")
for segment in line_segments:
    print(segment)




Unique line segments composing all the triangles:
((1, 2), (1, 3))
((0, 3), (1, 2))
((2, 2), (3, 1))
((1, 3), (2, 2))
((2, 2), (3, 2))
((1, 1), (2, 1))
((2, 1), (2, 2))
((1, 2), (2, 1))
((0, 1), (0, 2))
((1, 1), (1, 2))
((0, 2), (0, 3))
((0, 0), (1, 0))
((1, 2), (2, 2))
((0, 1), (1, 0))
((2, 1), (3, 1))
((0, 2), (1, 1))
((0, 1), (1, 1))
((1, 0), (1, 1))
((0, 0), (0, 1))
((0, 2), (1, 2))
((3, 1), (3, 2))


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [19]:
import numpy as np

def reconstruct_array(C):
    # Generate array indices based on bin counts
    indices = np.repeat(np.arange(len(C)), C)
    return indices

# Example usage
C = np.array([0, 2, 2, 0, 1])  # Example bincount array
A = reconstruct_array(C)

print("Original bincount array:", C)
print("Reconstructed array A:", A)
print("Result of np.bincount(A):", np.bincount(A))


Original bincount array: [0 2 2 0 1]
Reconstructed array A: [1 1 2 2 4]
Result of np.bincount(A): [0 2 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [7]:
import numpy as np

# Example sorted array C corresponding to bincount
C = np.array([1, 2, 2, 0, 1])

# Generate array A
A = np.repeat(np.arange(len(C)), C)

print("Array A:", A)
print("Result of np.bincount(A):", np.bincount(A))
print("Sorted array C:", np.sort(C))


Array A: [0 1 1 2 2 4]
Result of np.bincount(A): [1 2 2 0 1]
Sorted array C: [0 1 1 2 2]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
import numpy as np

# Example one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7])

# Number of elements to shift for each subsequent row
shift_amount = 1

# Calculate the number of rows needed
num_rows = len(Z) - shift_amount

# Initialize the two-dimensional array with zeros
result = np.zeros((num_rows, len(Z) - shift_amount))

# Fill the first row with the first elements of Z
result[0] = Z[:-shift_amount]

# Fill subsequent rows by shifting Z
for i in range(1, num_rows):
    result[i] = Z[i:i+len(Z)-shift_amount]

print("Original one-dimensional array Z:\n", Z)
print("\nTwo-dimensional array with shifted rows:\n", result)



#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [8]:
# Negate a Boolean
boolean_value = True
negated_boolean = not boolean_value
print("Original boolean:", boolean_value)
print("Negated boolean:", negated_boolean)


Original boolean: True
Negated boolean: False


In [9]:
# Change the Sign of a Float Inplace
float_value = 3.14
float_value *= -1
print("Original float:", float_value)


Original float: -3.14


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np

# Define two sets of points representing line segments (P0 and P1)
P0 = np.array([[1, 1], [2, 3], [4, 5]])
P1 = np.array([[4, 5], [5, 1], [7, 2]])

# Define the point p
p = np.array([2, 4])

# Vector from P0 to P1
v = P1 - P0

# Vector from P0 to p
w = p - P0

# Compute the dot product of w and v
dot_product = np.dot(w, v.T)

# Compute the squared length of each line segment
squared_length = np.sum(v**2, axis=1)

# Find the parameter t where t = dot_product / squared_length
t = np.clip(dot_product / squared_length, 0, 1)

# Reshape t to (3, 1, 1) to align with the shape of v
t = t[:, np.newaxis, np.newaxis]

# Compute the closest points on the line segments to the point p
closest_points = P0 + t * v[:, np.newaxis]

# Compute the distance between each closest point and p
distance = np.linalg.norm(closest_points - p, axis=2)

print("Distances from point p to each line segment:", distance)




#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [11]:
import numpy as np

def extract_subpart(array, center, shape, fill_value=0):
    """
    Extracts a subpart with a fixed shape centered on a given element.

    Parameters:
        array (numpy.ndarray): Input array.
        center (tuple): Coordinates of the center element.
        shape (tuple): Shape of the subpart to extract.
        fill_value (optional): Value used to fill elements outside the array boundaries.

    Returns:
        numpy.ndarray: Subpart of the array with the specified shape centered on the given element.
    """
    # Calculate the indices of the subpart
    start_indices = tuple(np.subtract(center, np.divide(shape, 2)).astype(int))
    end_indices = tuple(np.add(start_indices, shape))

    # Initialize the subpart array with fill values
    subpart = np.full(shape, fill_value)

    # Calculate the indices within the array boundaries
    clipped_start_indices = np.maximum(start_indices, 0)
    clipped_end_indices = np.minimum(end_indices, array.shape)

    # Calculate the indices within the subpart array
    subpart_start_indices = np.maximum(-np.array(start_indices), 0)
    subpart_end_indices = np.minimum(shape, np.array(shape) + (array.shape - np.array(end_indices)))

    # Copy the overlapping elements from the array to the subpart
    subpart[subpart_start_indices[0]:subpart_end_indices[0], subpart_start_indices[1]:subpart_end_indices[1]] = \
        array[clipped_start_indices[0]:clipped_end_indices[0], clipped_start_indices[1]:clipped_end_indices[1]]

    return subpart

# Example
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

center = (1, 2)
shape = (3, 3)
subpart = extract_subpart(array, center, shape, fill_value=-1)

print("Original Array:\n", array)
print("\nSubpart Centered at", center, "with Shape", shape, ":\n", subpart)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Subpart Centered at (1, 2) with Shape (3, 3) :
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)