<a href="https://colab.research.google.com/github/ericmuga253/Python-Data-/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.25.2


In [3]:
print(np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(zeros.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
zeros=np.zeros(10)
zeros[4]=1
print(zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector=np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector=np.arange(10,49)
print(np.flip(vector))

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
array=np.random.randint(0,8, size=(3,3))
print(array)

[[2 1 5]
 [1 2 1]
 [3 7 3]]


In [11]:
array=np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
array=np.array([1,2,0,0,4,0])
for values in array:
    if values != 0:
        print(values)


1
2
4


In [13]:
array=np.array([1,2,0,0,4,0])
print(np.nonzero(array))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
identity=np.eye(3,3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
array=np.random.random((3,3,3))
print(array)

[[[0.75277608 0.27598091 0.84433975]
  [0.836508   0.48574814 0.54034036]
  [0.7866053  0.15588681 0.35045629]]

 [[0.76821549 0.24601862 0.24609543]
  [0.39415135 0.37194306 0.61185157]
  [0.05135365 0.43424503 0.93480245]]

 [[0.52305891 0.63569912 0.506484  ]
  [0.87989373 0.10137697 0.61675047]
  [0.34726652 0.68135635 0.53884717]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
array=np.random.random((10,10))
print(array)

[[0.47931801 0.57481233 0.93247651 0.50303631 0.27735953 0.9698188
  0.73155571 0.43970863 0.5571116  0.96188356]
 [0.88685992 0.69155866 0.52239597 0.87086622 0.43964082 0.64297552
  0.99855037 0.96758686 0.26739724 0.38197216]
 [0.65833284 0.00516593 0.99393114 0.5531009  0.93235273 0.10533275
  0.82794519 0.01462638 0.41379538 0.96124618]
 [0.54350277 0.45354466 0.07171868 0.58062885 0.41808154 0.84055538
  0.92969272 0.37523833 0.00228266 0.56724665]
 [0.17656806 0.7768486  0.08116692 0.68939462 0.98866289 0.71340841
  0.72890263 0.08525009 0.77143419 0.99908333]
 [0.23350756 0.37982642 0.2823008  0.4207729  0.60478415 0.72265591
  0.4307791  0.28195281 0.32948354 0.51458788]
 [0.90950799 0.89207682 0.12950756 0.30793948 0.44732133 0.61844677
  0.93297425 0.14309803 0.3066475  0.13486483]
 [0.48361745 0.97747741 0.11019758 0.9699982  0.30792024 0.45264585
  0.0492793  0.50582931 0.24522728 0.4123265 ]
 [0.15983295 0.21425292 0.19038633 0.37957349 0.92574316 0.22127455
  0.37534174 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
vector=np.random.random(30)
print(vector)

[0.86057923 0.03347599 0.82258673 0.19694184 0.39726601 0.58519383
 0.10367301 0.20594853 0.25924543 0.82887097 0.13909903 0.32107254
 0.35610927 0.47205809 0.84546997 0.17273994 0.63750732 0.7946119
 0.93326084 0.15876719 0.39260834 0.57412755 0.1053578  0.51582943
 0.95486007 0.28366288 0.03014322 0.4393122  0.5708132  0.04349749]


In [18]:
vector.mean()


0.4344896608855628

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
values = [
    [1, 0, 1],
    [1, 0, 1],
    [1, 0, 1],
]
matrix = np.array(values)
print(matrix)

[[1 0 1]
 [1 0 1]
 [1 0 1]]
