<a href="https://colab.research.google.com/github/ericmuga253/Python-Data-/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [5]:
array=np.array([
    [2,3],
    [4,5],
    [5,6]
])
print(array)

# shape of rows and columns
rows, columns=array.shape
print(rows, columns)

zero_border=np.zeros((rows+2, columns+2),dtype=array.dtype)

zero_border[1:-1, 1:-1]=array
print(zero_border)

[[2 3]
 [4 5]
 [5 6]]
3 2
[[0 0 0 0]
 [0 2 3 0]
 [0 4 5 0]
 [0 5 6 0]
 [0 0 0 0]]


In [15]:
group =np.array([
    [2,3,1],
    [4,5,1],
    [6,7,2]

    ])
print(group[-1,-1])

2


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1 )


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [25]:
array=np.zeros((5,5))
# print(array)
np.fill_diagonal(array[1:],[1,2,3,4])

print(array)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
array=np.zeros((8,8),dtype=int)
print(array)

array[::2,::2]=1
print(array)


array[1::2,1::2]=1
print(array)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
array=np.arange(336).reshape(6,7,8)
print(array)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [45]:
array = np.arange(336).reshape(6, 7, 8)

# Find the index of the 100th element
index = np.unravel_index(99, array.shape)

print("Index of the 100th element:", index)

Index of the 100th element: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [46]:
tile = np.array([[0, 1],
                 [1, 0]])

# Use tile() function to create an 8x8 checkerboard matrix
checkerboard = np.tile(tile, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [47]:
matrix=np.random.normal(1,2.5,size=(5,5))
print(matrix)

[[ 3.52970212 -0.04418542  3.34117    -1.15598942 -1.71880024]
 [ 0.6704122  -0.62695068  2.26624696  0.52092824  0.43991764]
 [-1.9411398  -0.81510366  4.11896983  3.84785216  1.27310255]
 [ 4.14034005  4.78715928  2.85487047  0.89618299  2.55646993]
 [ 1.32004495 -1.094925    3.76541227  0.81258999  3.03365395]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [48]:
array1=np.arange(15).reshape(5,3)
array2=np.arange(6).reshape(3,2)
array3=array1*array2
print(array3)

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [54]:
Z=1
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

1
1
False
1j
1.0
False


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-55-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-55-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-55-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [57]:
print(np.ceil(4.1))

5.0


In [59]:
print(np.floor(4.9))

4.0


In [60]:

arr = np.array([-1.5, 2.7, -3.3, 4.1])

rounded_arr = np.where(arr >= 0, np.ceil(arr), np.floor(arr))

print("Original Array:", arr)
print("Rounded Away from Zero Array:", rounded_arr)

Original Array: [-1.5  2.7 -3.3  4.1]
Rounded Away from Zero Array: [-2.  3. -4.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [61]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)

Common values: [3 4 5]
